### ISSUE TITLE
Build error on GHC 9.2.1

### ISSUE THREAD

**Issue by bruno-cadorette** [dorchard/type-level-sets#31]
```
Warning: type-level-sets.cabal:84:3: The field "other-extensions" is available
only since the Cabal specification version 1.10.
Configuring type-level-sets-0.8.9.0...
Preprocessing library for type-level-sets-0.8.9.0..
Building library for type-level-sets-0.8.9.0..
[1 of 2] Compiling Data.Type.Set    ( src/Data/Type/Set.hs, dist/build/Data/Type/Set.o, dist/build/Data/Type/Set.dyn_o )

src/Data/Type/Set.hs:53:1: error:
    • Uninferrable type variables k0, k1 in
      the type synonym right-hand side:
      ((Union @{k} f ('[] @k) :: [k]) ~ (f :: [k]),
       Split @{k} @{k0} @{k} f ('[] @k0) f,
       (Union @{k} ('[] @k) f :: [k]) ~ (f :: [k]),
       Split @{k1} @{k} @{k} ('[] @k1) f f,
       (Union @{k} f f :: [k]) ~ (f :: [k]), Split @{k} @{k} @{k} f f f,
       Unionable @{k} f ('[] @k), Unionable @{k} ('[] @k) f)
    • In the type declaration for ‘SetProperties’
   |
53 | type SetProperties f = (Union f '[] ~ f, Split f '[] f,
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...

```

**Comment by raehik** [comment]
Fixed in #29 (which I'll ping dorchard about next week!)

**Comment by dorchard** [comment]
Merged the fix.

**Comment by sjakobi** [comment]
As a Hackage trustee, I have revised `type-level-sets-0.8.9.0` with a bound `base < 4.16` to prevent builds with GHC >= 9.2.

Could you upload a release that includes the fix (#29)?
